//Types for reducers
const types = {
	USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
	USER_REGISTER_ERROR: 'USER_REGISTER_ERROR',
	CLEAR_MESSAGE: 'CLEAR_MESSAGE',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_ERROR: 'LOGIN_ERROR',
	LOADING: 'LOADING',
	LOADING_APP: 'LOADING_APP',
	AUTHENTICATE_USER: 'AUTHENTICATE_USER',
	LOGOUT: 'LOGOUT',
	GET_OPERATIONS: 'GET_OPERATIONS',
	GET_OPERATION_BY_ID: 'GET_OPERATION_BY_ID'
}

export default types
